---
- name: creating variables
  hosts: webservers
  tasks:
    - name: create directory
      ansible.builtin.file:
        path: "{{directory}}"
        state: directory
    - name: create files
      ansible.builtin.file:
        path: "{{file}}"
        state: touch
    - name: copy content
      ansible.builtin.copy:
        content: "{{content}}"
        dest: "{{directory}}/{{file}}"
